import {useMemo,useState} from 'react';
import {Activity,CloudRain,Database,Leaf,MapPin,Play,Pause,Radio,Telescope,WalletCards,Wind} from 'lucide-react';
import {simulateClimateAction,Objective} from '@terramavuno/shared';
import {MapView} from './components/MapView';
import {counties,layers,LayerKey,timeline} from './data';

export function App(){
 const [selected,setSelected]=useState('Makueni'),[compare,setCompare]=useState('Nakuru'),[year,setYear]=useState(2024),[playing,setPlaying]=useState(false); const [active,setActive]=useState<Set<LayerKey>>(new Set(['rainfall','drought','vegetation'])); const [budget,setBudget]=useState(10_000_000),[objective,setObjective]=useState<Objective>('drought-resilience');
 const county=counties.find(c=>c.name===selected)!; const other=counties.find(c=>c.name===compare)!; const options=useMemo(()=>simulateClimateAction({county:selected,budgetKes:budget,objective,horizonYears:3}),[selected,budget,objective]); const top=options[0]; const t=timeline.find(x=>x.year===year)!;
 function toggle(k:LayerKey){setActive(s=>{const n=new Set(s);n.has(k)?n.delete(k):n.add(k);return n})}
 function play(){setPlaying(true);let y=2020;setYear(y);const timer=setInterval(()=>{y++;if(y>2025){clearInterval(timer);setPlaying(false);return}setYear(y)},700)}
 return <main><header><div className="brand"><div className="mark"><Leaf/></div><div><h1>TERRA<span>MAVUNO</span></h1><p>Kenya Climate Action Console</p></div></div><div className="status"><i/> DEMO DATA • SOURCED BENCHMARKS <span>02 SEP 2026 • EAT</span></div></header>
 <div className="layout"><aside className="left-panel"><PanelTitle icon={<MapPin/>} title="County focus"/><select value={selected} onChange={e=>setSelected(e.target.value)}>{counties.map(c=><option key={c.name}>{c.name}</option>)}</select><div className="coordinate">{county.lat.toFixed(3)}°, {county.lng.toFixed(3)}°</div>
 <PanelTitle icon={<Database/>} title="Evidence layers"/>{layers.map(l=><button className={'layer '+(active.has(l.key)?'active':'')} key={l.key} onClick={()=>toggle(l.key)}><i style={{background:l.color}}/><span>{l.label}<small>{l.source}<br/>{l.freshness} • {l.confidence}</small></span><b>{active.has(l.key)?'ON':'OFF'}</b></button>)}
 <PanelTitle icon={<Telescope/>} title="Spatial command"/><div className="command">“Fly to {selected}. Outline the county. Show drought, rainfall and water assets. Replay from 2020.”<button>Voice-ready command</button></div></aside>
 <section className="center"><MapView selected={selected} onSelect={setSelected} activeLayers={active} year={year}/><div className="timeline"><button onClick={playing?()=>setPlaying(false):play}>{playing?<Pause/>:<Play/>}</button><div><div className="year-row">{timeline.map(x=><button className={x.year===year?'current':''} onClick={()=>setYear(x.year)} key={x.year}>{x.year}</button>)}</div><input type="range" min="2020" max="2025" value={year} onChange={e=>setYear(+e.target.value)}/></div><div className="signal"><CloudRain/> Rain {t.rain}<Wind/> Drought {t.drought}<Leaf/> NDVI {t.ndvi}</div></div>
 <div className="metrics"><Metric label="Rainfall benchmark" value={`${county.rain} mm`} delta={`${t.rain}/100 index`}/><Metric label="Drought stress" value={`${Math.min(100,county.drought+(year-2024)*2)}/100`} delta={county.trend}/><Metric label="Vegetation NDVI" value={county.ndvi.toFixed(2)} delta="satellite-compatible"/><Metric label="Water access" value={`${county.water}%`} delta="demo estimate"/></div></section>
 <aside className="right-panel"><PanelTitle icon={<WalletCards/>} title="Climate Action Simulator"/><div className="notice">SIMULATED BENCHMARK • NOT AN OFFICIAL COST ESTIMATE</div><label>Budget (KES)<input type="number" value={budget} step={1000000} onChange={e=>setBudget(Math.max(1,+e.target.value))}/></label><label>Objective<select value={objective} onChange={e=>setObjective(e.target.value as Objective)}><option value="drought-resilience">Reduce drought vulnerability</option><option value="food-security">Improve food security</option><option value="farmer-income">Increase farmer income</option><option value="water-security">Improve water security</option></select></label><label>Horizon<select><option>3 years</option></select></label>
 <div className="winner"><small>TOP-RANKED DEMO OPTION</small><h3>{top.name}</h3><b>KES {(top.allocatedKes/1e6).toFixed(1)}M</b><div className="winner-grid"><span><strong>{top.beneficiaries.toLocaleString()}</strong> people/HH equivalents</span><span><strong>{top.expectedImpact}/100</strong> expected impact</span><span><strong>{top.suitability}/100</strong> suitability</span><span><strong>{top.implementationMonths} mo</strong> implementation</span></div></div>
 <div className="rankings">{options.map((o,i)=><div key={o.kind}><b>{i+1}</b><span>{o.name}<small>{o.evidenceStrength} evidence • {o.beneficiaries.toLocaleString()} reached</small></span><strong>{o.expectedImpact}</strong></div>)}</div>
 <PanelTitle icon={<Activity/>} title="County comparison"/><div className="compare"><select value={compare} onChange={e=>setCompare(e.target.value)}>{counties.filter(c=>c.name!==selected).map(c=><option key={c.name}>{c.name}</option>)}</select><CompareRow label="Drought" a={county.drought} b={other.drought}/><CompareRow label="Rainfall" a={Math.round(county.rain/13)} b={Math.round(other.rain/13)}/><CompareRow label="Water" a={county.water} b={other.water}/></div></aside></div>
 <footer><Radio/> LIVE CONNECTIONS DISABLED IN DEMO <span>Every visible signal includes source, freshness and confidence metadata. Values shown are illustrative benchmarks, not official findings.</span></footer></main>
}
function PanelTitle({icon,title}:{icon:React.ReactNode,title:string}){return <h2 className="panel-title">{icon}{title}</h2>}
function Metric({label,value,delta}:{label:string,value:string,delta:string}){return <div className="metric"><small>{label}</small><strong>{value}</strong><span>{delta}</span></div>}
function CompareRow({label,a,b}:{label:string,a:number,b:number}){return <div className="compare-row"><small>{label}</small><div><i style={{width:`${a}%`}}/></div><b>{a}</b><div><i style={{width:`${b}%`}}/></div><b>{b}</b></div>}

