// Generated by scripts/generate-kenya-seed.mjs inputs (references/kenya-locations, MIT, David Amunga).
// Do not hand-edit: regenerate from data/kenya-counties.json.
export interface County { code: string; name: string; slug: string }
export const counties: readonly County[] = [
  {code:'030',name:'Baringo',slug:'baringo'},
  {code:'036',name:'Bomet',slug:'bomet'},
  {code:'039',name:'Bungoma',slug:'bungoma'},
  {code:'040',name:'Busia',slug:'busia'},
  {code:'028',name:'Elgeyo-Marakwet',slug:'elgeyo-marakwet'},
  {code:'014',name:'Embu',slug:'embu'},
  {code:'007',name:'Garissa',slug:'garissa'},
  {code:'043',name:'Homa Bay',slug:'homa-bay'},
  {code:'011',name:'Isiolo',slug:'isiolo'},
  {code:'034',name:'Kajiado',slug:'kajiado'},
  {code:'037',name:'Kakamega',slug:'kakamega'},
  {code:'035',name:'Kericho',slug:'kericho'},
  {code:'022',name:'Kiambu',slug:'kiambu'},
  {code:'003',name:'Kilifi',slug:'kilifi'},
  {code:'020',name:'Kirinyaga',slug:'kirinyaga'},
  {code:'045',name:'Kisii',slug:'kisii'},
  {code:'042',name:'Kisumu',slug:'kisumu'},
  {code:'015',name:'Kitui',slug:'kitui'},
  {code:'002',name:'Kwale',slug:'kwale'},
  {code:'031',name:'Laikipia',slug:'laikipia'},
  {code:'005',name:'Lamu',slug:'lamu'},
  {code:'016',name:'Machakos',slug:'machakos'},
  {code:'017',name:'Makueni',slug:'makueni'},
  {code:'009',name:'Mandera',slug:'mandera'},
  {code:'010',name:'Marsabit',slug:'marsabit'},
  {code:'012',name:'Meru',slug:'meru'},
  {code:'044',name:'Migori',slug:'migori'},
  {code:'001',name:'Mombasa',slug:'mombasa'},
  {code:'021',name:'Murang\'a',slug:'murang-a'},
  {code:'047',name:'Nairobi',slug:'nairobi'},
  {code:'032',name:'Nakuru',slug:'nakuru'},
  {code:'029',name:'Nandi',slug:'nandi'},
  {code:'033',name:'Narok',slug:'narok'},
  {code:'046',name:'Nyamira',slug:'nyamira'},
  {code:'018',name:'Nyandarua',slug:'nyandarua'},
  {code:'019',name:'Nyeri',slug:'nyeri'},
  {code:'025',name:'Samburu',slug:'samburu'},
  {code:'041',name:'Siaya',slug:'siaya'},
  {code:'006',name:'Taita-Taveta',slug:'taita-taveta'},
  {code:'004',name:'Tana River',slug:'tana-river'},
  {code:'013',name:'Tharaka-Nithi',slug:'tharaka-nithi'},
  {code:'026',name:'Trans Nzoia',slug:'trans-nzoia'},
  {code:'023',name:'Turkana',slug:'turkana'},
  {code:'027',name:'Uasin Gishu',slug:'uasin-gishu'},
  {code:'038',name:'Vihiga',slug:'vihiga'},
  {code:'008',name:'Wajir',slug:'wajir'},
  {code:'024',name:'West Pokot',slug:'west-pokot'}
];

const normalize = (s: string) => s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '');

/** Resolve free-text input from a USSD keypad or SMS body to a county. Exact, then prefix, then contains. */
export function matchCounty(input: string): County | null {
  const q = normalize(input);
  if (!q) return null;
  const byCode = counties.find(c => c.code === input.trim().padStart(3, '0'));
  if (byCode) return byCode;
  return counties.find(c => normalize(c.name) === q)
    ?? counties.find(c => normalize(c.name).startsWith(q))
    ?? (q.length >= 4 ? counties.find(c => normalize(c.name).includes(q)) ?? null : null);
}
