const location = {type:'string', description:'Kenyan county, ward, locality, or coordinates'};
export const claudeTools = [
  {name:'map_action',description:'Navigate and control the agricultural map.',input_schema:{type:'object',properties:{action:{type:'string',enum:['fly_to','orbit','outline','toggle_layer','nearby','measure_distance','animate_route','terrain','temporal_replay']},location,layer:{type:'string'},enabled:{type:'boolean'},year:{type:'integer',minimum:2020}},required:['action']}},
  {name:'compare_locations',description:'Compare agriculture and climate signals between locations.',input_schema:{type:'object',properties:{locations:{type:'array',items:location,minItems:2},indicators:{type:'array',items:{type:'string'}},year:{type:'integer',minimum:2020}},required:['locations']}},
  {name:'get_climate_history',description:'Retrieve sourced time-series observations.',input_schema:{type:'object',properties:{location,indicators:{type:'array',items:{type:'string'}},from_year:{type:'integer',minimum:2020},to_year:{type:'integer',minimum:2020}},required:['location','from_year','to_year']}},
  {name:'search_budgets',description:'Search county or programme budgets.',input_schema:{type:'object',properties:{location,query:{type:'string'},fiscal_year:{type:'string'}},required:['location']}},
  {name:'search_programmes',description:'Search agricultural programmes and projects.',input_schema:{type:'object',properties:{location,query:{type:'string'},status:{type:'string'}},required:['location']}},
  {name:'simulate_climate_action',description:'Compare explicitly simulated budget-to-impact intervention options.',input_schema:{type:'object',properties:{county:{type:'string'},budget_kes:{type:'number',exclusiveMinimum:0},objective:{type:'string',enum:['drought-resilience','food-security','farmer-income','water-security']},horizon_years:{type:'integer',minimum:1,maximum:20}},required:['county','budget_kes','objective','horizon_years']}},
  {name:'generate_report',description:'Generate a sourced decision report.',input_schema:{type:'object',properties:{title:{type:'string'},location,sections:{type:'array',items:{type:'string'}},format:{type:'string',enum:['markdown','pdf','docx']}},required:['title','location']}},
  {name:'send_report',description:'Send a generated report through an approved channel.',input_schema:{type:'object',properties:{report_id:{type:'string'},channel:{type:'string',enum:['email','sms','whatsapp']},recipient:{type:'string'},confirm:{type:'boolean'}},required:['report_id','channel','recipient','confirm']}}
] as const;

