const location = {type:'string', description:'Kenyan county, ward, locality, or coordinates'};
export const farmerChannels = ['ussd','sms','ivr','whatsapp','web'] as const;
export type FarmerChannel = (typeof farmerChannels)[number];
export const claudeTools = [
  {name:'map_action',description:'Navigate and control the agricultural map.',input_schema:{type:'object',properties:{action:{type:'string',enum:['fly_to','orbit','outline','toggle_layer','nearby','measure_distance','animate_route','terrain','temporal_replay']},location,layer:{type:'string'},enabled:{type:'boolean'},year:{type:'integer',minimum:2020}},required:['action']}},
  {name:'compare_locations',description:'Compare agriculture and climate signals between locations.',input_schema:{type:'object',properties:{locations:{type:'array',items:location,minItems:2},indicators:{type:'array',items:{type:'string'}},year:{type:'integer',minimum:2020}},required:['locations']}},
  {name:'get_climate_history',description:'Retrieve sourced time-series observations.',input_schema:{type:'object',properties:{location,indicators:{type:'array',items:{type:'string'}},from_year:{type:'integer',minimum:2020},to_year:{type:'integer',minimum:2020}},required:['location','from_year','to_year']}},
  {name:'search_budgets',description:'Search county or programme budgets.',input_schema:{type:'object',properties:{location,query:{type:'string'},fiscal_year:{type:'string'}},required:['location']}},
  {name:'search_programmes',description:'Search agricultural programmes and projects.',input_schema:{type:'object',properties:{location,query:{type:'string'},status:{type:'string'}},required:['location']}},
  {name:'simulate_climate_action',description:'Compare explicitly simulated budget-to-impact intervention options.',input_schema:{type:'object',properties:{county:{type:'string'},budget_kes:{type:'number',exclusiveMinimum:0},objective:{type:'string',enum:['drought-resilience','food-security','farmer-income','water-security']},horizon_years:{type:'integer',minimum:1,maximum:20}},required:['county','budget_kes','objective','horizon_years']}},
  {name:'generate_report',description:'Generate a sourced decision report.',input_schema:{type:'object',properties:{title:{type:'string'},location,sections:{type:'array',items:{type:'string'}},format:{type:'string',enum:['markdown','pdf','docx']}},required:['title','location']}},
  {name:'send_report',description:'Send a generated report or advisory summary through an approved channel. USSD and SMS are the feature-phone path to farmers affected by a decision; keep the payload short enough for a 160-character segment when the channel is sms or ussd.',input_schema:{type:'object',properties:{report_id:{type:'string'},channel:{type:'string',enum:['email','sms','ussd','whatsapp']},recipient:{type:'string',description:'Email address, or a hashed channel identity for phone channels. Never pass a raw phone number.'},confirm:{type:'boolean'}},required:['report_id','channel','recipient','confirm']}},
  {name:'record_field_report',description:'Record an inbound report from a farmer or field officer arriving over a farmer channel. This is the return path that lets the field confirm, contradict or supplement a modelled claim. Stored as community-classified, unverified evidence; it is never promoted to official data without a verification step.',input_schema:{type:'object',properties:{channel:{type:'string',enum:['ussd','sms','ivr','whatsapp','web']},location,observation:{type:'string',description:"What the reporter said, in their own words"},indicator:{type:'string',description:'Optional structured indicator, e.g. rainfall_onset, seed_delivered, borehole_status, crop_loss_percent'},value:{type:'number'},unit:{type:'string'},observed_at:{type:'string',description:'ISO 8601 time of the observation itself, not of the message'},reporter_ref:{type:'string',description:'Salted hash of the channel identity. Never pass a raw phone number or MSISDN.'},confidence:{type:'string',enum:['high','moderate','limited','unknown']}},required:['channel','location','observation']}}
] as const;

